# Generated by Django 4.1 on 2022-09-08 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunities", "0002_alter_opportunity_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunityrequirement",
            name="opportunity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirements",
                to="opportunities.opportunity",
                verbose_name="opportunity",
            ),
        ),
    ]
