# Generated by Django 4.1 on 2022-09-13 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunities", "0003_alter_opportunityrequirement_opportunity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunityrequirement",
            name="weight",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
