# Generated by Django 4.1 on 2022-09-18 02:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunities", "0006_opportunityanswer_opportunityanswerrequirement"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunityrequirement",
            name="minimim_knowledge",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
