apiVersion: v1
kind: Service
metadata:
  name: venturahr
spec:
  type: NodePort
  selector:
    app: venturahr
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      nodePort: 30000

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
