version: "3"

services:
  venturahr_db:
    image: postgres:14.3
    # You can all queries executed on the database by uncomment this
#    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - venturahr_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - venturahr_net

  # Django doesn't like underscores in the service name when receiving a request.
  venturahrapi:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: infnet/venturahr-api:local
    container_name: venturahrapi
    command: python manage.py runserver 0.0.0.0:8081
    env_file:
      - .env.default
    volumes:
      - ./backend/:/app/backend/
    ports:
      - "8081:8081"
    networks:
      - venturahr_net
    depends_on:
      - venturahr_db

  venturahr_migrator:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: infnet/venturahr-api:local
    container_name: venturahr_migrator
    command: python manage.py migrate
    env_file:
      - .env.default
    volumes:
      - ./backend/:/app/backend/
    networks:
      - venturahr_net
    depends_on:
      - venturahr_db

  # Monitoring
  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    volumes:
      - ./.prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - venturahr_net
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    depends_on:
      - venturahrapi

  grafana:
    image: grafana/grafana:8.2.6
    ports:
      - "9091:3000"
    volumes:
      - ./.grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana
    networks:
      - venturahr_net

volumes:
  venturahr_db_data: {}
  prometheus_data: {}
  grafana_data: {}

networks:
  venturahr_net:
    driver: bridge
