global:
  scrape_interval: 10s
  scrape_timeout: 5s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    scrape_timeout: 30s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'venturahrapi'
    static_configs:
      - targets: ['venturahrapi:8081']

rule_files:
  - "venturahr.rules"
